/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  ALL_DONE_VIEW_TYPE: () => ALL_DONE_VIEW_TYPE,
  AllDoneTodosView: () => AllDoneTodosView,
  KANBAN_VIEW_TYPE: () => KANBAN_VIEW_TYPE,
  KanbanSkillChartView: () => KanbanSkillChartView,
  KanbanView: () => KanbanView,
  SKILL_CHART_VIEW_TYPE: () => SKILL_CHART_VIEW_TYPE,
  default: () => KanbanTodoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function generateId() {
  return Math.random().toString(36).substring(2, 10) + Date.now().toString(36);
}
function toDateInputVal(d) {
  return d.toISOString().slice(0, 10);
}
function wrapText(text, maxLen) {
  if (text.length <= maxLen)
    return [text];
  const words = text.split(" ");
  const lines = [];
  let cur = "";
  for (const w of words) {
    const test = cur ? cur + " " + w : w;
    if (test.length > maxLen && cur) {
      lines.push(cur);
      cur = w;
    } else
      cur = test;
  }
  if (cur)
    lines.push(cur);
  return lines;
}
function escSvg(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var ONE_WEEK_MS = 7 * 24 * 60 * 60 * 1e3;
var DEFAULT_SETTINGS = {
  labels: [
    { id: generateId(), name: "Bug", color: "#ef4444" },
    { id: generateId(), name: "Feature", color: "#6366f1" },
    { id: generateId(), name: "Idea", color: "#f59e0b" },
    { id: generateId(), name: "Important", color: "#10b981" }
  ],
  skillData: { scores: {}, snapshots: [] }
};
function defaultBoard() {
  return {
    columns: [
      { id: generateId(), name: "Backlog", cards: [], color: "#6366f1" },
      { id: generateId(), name: "In Progress", cards: [], color: "#f59e0b" },
      { id: generateId(), name: "Done", cards: [], color: "#10b981", isDone: true }
    ]
  };
}
var KANBAN_VIEW_TYPE = "kanban-todo-view";
var KanbanView = class extends import_obsidian.TextFileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.boardData = defaultBoard();
    this.draggedCard = null;
    this.plugin = plugin;
  }
  getViewType() {
    return KANBAN_VIEW_TYPE;
  }
  getDisplayText() {
    var _a, _b;
    return (_b = (_a = this.file) == null ? void 0 : _a.basename) != null ? _b : "Kanban Board";
  }
  getIcon() {
    return "layout-dashboard";
  }
  getViewData() {
    return JSON.stringify(this.boardData, null, 2);
  }
  setViewData(data, _clear) {
    try {
      const parsed = JSON.parse(data);
      this.boardData = (parsed == null ? void 0 : parsed.columns) ? parsed : defaultBoard();
    } catch (e) {
      this.boardData = defaultBoard();
    }
    this.render();
  }
  clear() {
    this.boardData = defaultBoard();
  }
  async persist() {
    this.requestSave();
    this.render();
  }
  async moveCard(card, fromCol, toCol) {
    var _a, _b;
    const idx = fromCol.cards.findIndex((c) => c.id === card.id);
    if (idx === -1)
      return;
    fromCol.cards.splice(idx, 1);
    if (fromCol.isDone && ((_a = card.labelIds) == null ? void 0 : _a.length)) {
      await this.plugin.updateSkillScores(card.labelIds, -1);
    }
    if (toCol.isDone) {
      card.completedAt = Date.now();
      if ((_b = card.labelIds) == null ? void 0 : _b.length)
        await this.plugin.updateSkillScores(card.labelIds, 1);
    } else {
      delete card.completedAt;
    }
    toCol.cards.push(card);
    await this.persist();
    this.plugin.refreshAllDoneView();
  }
  render() {
    var _a, _b;
    const el = this.contentEl;
    el.empty();
    el.addClass("kanban-root");
    const hdr = el.createEl("div", { cls: "kanban-header" });
    hdr.createEl("span", { cls: "kanban-header-title", text: (_b = (_a = this.file) == null ? void 0 : _a.basename) != null ? _b : "Board" });
    const renameBtn = hdr.createEl("button", { cls: "kanban-rename-btn", attr: { title: "Rename board" } });
    renameBtn.innerHTML = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>`;
    renameBtn.addEventListener("click", () => {
      if (!this.file)
        return;
      new InputModal(this.app, "Rename board", this.file.basename, async (val) => {
        var _a2;
        if (this.file) {
          const newPath = ((_a2 = this.file.parent) == null ? void 0 : _a2.path) ? `${this.file.parent.path}/${val}.kanban` : `${val}.kanban`;
          await this.app.fileManager.renameFile(this.file, newPath);
        }
      }).open();
    });
    const board = el.createEl("div", { cls: "kanban-board" });
    this.boardData.columns.forEach((col) => this.renderColumn(board, col));
    const addColBtn = board.createEl("button", { cls: "kanban-add-col-btn", attr: { title: "Add column" } });
    addColBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>`;
    addColBtn.addEventListener("click", () => {
      new ColumnModal(this.app, { name: "New Column", isDone: false }, async ({ name, isDone }) => {
        this.boardData.columns.push({ id: generateId(), name, cards: [], color: "#8b5cf6", isDone });
        await this.persist();
      }).open();
    });
  }
  renderColumn(board, col) {
    var _a, _b;
    const now = Date.now();
    const visibleCards = col.isDone ? col.cards.filter((c) => !c.completedAt || now - c.completedAt < ONE_WEEK_MS) : col.cards;
    const hiddenCount = col.isDone ? col.cards.length - visibleCards.length : 0;
    const colEl = board.createEl("div", { cls: "kanban-col" + (col.isDone ? " kanban-col-done" : "") });
    const hdr = colEl.createEl("div", { cls: "kanban-col-hdr" });
    const accent = hdr.createEl("span", { cls: "kanban-col-accent" });
    accent.style.background = (_a = col.color) != null ? _a : "#6366f1";
    const titleEl = hdr.createEl("span", { cls: "kanban-col-title", text: col.name });
    if (col.isDone) {
      const doneTag = hdr.createEl("span", { cls: "kanban-done-tag", text: "done", attr: { title: "This is the Done column" } });
    }
    titleEl.addEventListener("dblclick", () => {
      var _a2;
      new ColumnModal(this.app, { name: col.name, isDone: (_a2 = col.isDone) != null ? _a2 : false }, async ({ name, isDone }) => {
        var _a3, _b2;
        const wasInDone = col.isDone;
        const becomingDone = isDone && !wasInDone;
        const leavingDone = !isDone && wasInDone;
        if (leavingDone) {
          for (const card of col.cards) {
            if ((_a3 = card.labelIds) == null ? void 0 : _a3.length)
              await this.plugin.updateSkillScores(card.labelIds, -1);
            delete card.completedAt;
          }
        }
        if (becomingDone) {
          for (const card of col.cards) {
            if (!card.completedAt)
              card.completedAt = Date.now();
            if ((_b2 = card.labelIds) == null ? void 0 : _b2.length)
              await this.plugin.updateSkillScores(card.labelIds, 1);
          }
        }
        col.name = name;
        col.isDone = isDone;
        await this.persist();
        this.plugin.refreshAllDoneView();
      }).open();
    });
    const badge = hdr.createEl("span", { cls: "kanban-col-badge", text: String(col.cards.length) });
    badge.style.background = (_b = col.color) != null ? _b : "#6366f1";
    const del = hdr.createEl("button", { cls: "kb-icon-btn", attr: { title: "Delete column" } });
    del.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v6M14 11v6"/><path d="M9 6V4h6v2"/></svg>`;
    del.addEventListener("click", async () => {
      var _a2;
      if (col.cards.length > 0 && !confirm(`Delete "${col.name}" with ${col.cards.length} card(s)?`))
        return;
      if (col.isDone) {
        for (const card of col.cards) {
          if ((_a2 = card.labelIds) == null ? void 0 : _a2.length)
            await this.plugin.updateSkillScores(card.labelIds, -1);
        }
      }
      this.boardData.columns = this.boardData.columns.filter((c) => c.id !== col.id);
      await this.persist();
      this.plugin.refreshAllDoneView();
    });
    const cardsEl = colEl.createEl("div", { cls: "kanban-cards" });
    cardsEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      colEl.addClass("drag-over");
    });
    cardsEl.addEventListener("dragleave", (e) => {
      if (!colEl.contains(e.relatedTarget))
        colEl.removeClass("drag-over");
    });
    cardsEl.addEventListener("drop", async (e) => {
      e.preventDefault();
      colEl.removeClass("drag-over");
      if (!this.draggedCard)
        return;
      const { card, sourceCol } = this.draggedCard;
      if (sourceCol.id === col.id)
        return;
      this.draggedCard = null;
      await this.moveCard(card, sourceCol, col);
    });
    visibleCards.forEach((card) => this.renderCard(cardsEl, card, col));
    if (hiddenCount > 0) {
      const archivedNote = cardsEl.createEl("div", { cls: "kanban-archived-note" });
      archivedNote.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="21 8 21 21 3 21 3 8"/><rect x="1" y="3" width="22" height="5"/><line x1="10" y1="12" x2="14" y2="12"/></svg> ${hiddenCount} completed item${hiddenCount > 1 ? "s" : ""} archived`;
    }
    const addBtn = colEl.createEl("button", { cls: "kanban-add-card-btn" });
    addBtn.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg><span>Add card</span>`;
    addBtn.addEventListener("click", () => {
      new CardModal(this.app, this.plugin.settings.labels, null, async (title, desc, labelIds) => {
        const card = { id: generateId(), title, description: desc, labelIds, createdAt: Date.now() };
        if (col.isDone) {
          card.completedAt = Date.now();
          if (labelIds.length)
            await this.plugin.updateSkillScores(labelIds, 1);
        }
        col.cards.push(card);
        await this.persist();
        this.plugin.refreshAllDoneView();
      }).open();
    });
  }
  renderCard(container, card, col) {
    const el = container.createEl("div", { cls: "kanban-card", attr: { draggable: "true" } });
    el.addEventListener("dragstart", (e) => {
      var _a;
      this.draggedCard = { card, sourceCol: col };
      el.addClass("dragging");
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", card.id);
    });
    el.addEventListener("dragend", () => {
      el.removeClass("dragging");
      this.draggedCard = null;
      document.querySelectorAll(".drag-over").forEach((n) => n.removeClass("drag-over"));
    });
    const body = el.createEl("div", { cls: "kanban-card-body" });
    body.createEl("div", { cls: "kanban-card-title", text: card.title });
    if (card.description)
      body.createEl("div", { cls: "kanban-card-desc", text: card.description });
    const cardLabels = this.plugin.settings.labels.filter((l) => {
      var _a;
      return (_a = card.labelIds) == null ? void 0 : _a.includes(l.id);
    });
    if (cardLabels.length) {
      const row = el.createEl("div", { cls: "kanban-card-labels" });
      cardLabels.forEach((l) => {
        const tag = row.createEl("span", { cls: "kanban-label-tag", text: l.name });
        tag.style.setProperty("--lc", l.color);
      });
    }
    const footer = el.createEl("div", { cls: "kanban-card-footer" });
    const actions = footer.createEl("div", { cls: "kanban-card-actions" });
    const colIdx = this.boardData.columns.findIndex((c) => c.id === col.id);
    if (colIdx > 0) {
      const lb = actions.createEl("button", { cls: "kb-icon-btn", attr: { title: "Move left" } });
      lb.innerHTML = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="15 18 9 12 15 6"/></svg>`;
      lb.addEventListener("click", async (e) => {
        e.stopPropagation();
        await this.moveCard(card, col, this.boardData.columns[colIdx - 1]);
      });
    }
    if (colIdx < this.boardData.columns.length - 1) {
      const rb = actions.createEl("button", { cls: "kb-icon-btn", attr: { title: "Move right" } });
      rb.innerHTML = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"/></svg>`;
      rb.addEventListener("click", async (e) => {
        e.stopPropagation();
        await this.moveCard(card, col, this.boardData.columns[colIdx + 1]);
      });
    }
    const editBtn = actions.createEl("button", { cls: "kb-icon-btn", attr: { title: "Edit" } });
    editBtn.innerHTML = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>`;
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      new CardModal(this.app, this.plugin.settings.labels, card, async (title, desc, labelIds) => {
        var _a;
        if (col.isDone && ((_a = card.labelIds) == null ? void 0 : _a.length))
          await this.plugin.updateSkillScores(card.labelIds, -1);
        card.title = title;
        card.description = desc;
        card.labelIds = labelIds;
        if (col.isDone && labelIds.length)
          await this.plugin.updateSkillScores(labelIds, 1);
        await this.persist();
        this.plugin.refreshAllDoneView();
      }).open();
    });
    const delBtn = actions.createEl("button", { cls: "kb-icon-btn kb-icon-danger", attr: { title: "Delete" } });
    delBtn.innerHTML = `<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;
    delBtn.addEventListener("click", async (e) => {
      var _a;
      e.stopPropagation();
      if (col.isDone && ((_a = card.labelIds) == null ? void 0 : _a.length))
        await this.plugin.updateSkillScores(card.labelIds, -1);
      col.cards = col.cards.filter((c) => c.id !== card.id);
      await this.persist();
      this.plugin.refreshAllDoneView();
    });
  }
};
var ALL_DONE_VIEW_TYPE = "kanban-all-done";
var AllDoneTodosView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return ALL_DONE_VIEW_TYPE;
  }
  getDisplayText() {
    return "All Done Todos";
  }
  getIcon() {
    return "check-square";
  }
  async onOpen() {
    await this.render();
  }
  async onClose() {
  }
  async render() {
    var _a;
    const el = this.contentEl;
    el.empty();
    el.addClass("kanban-done-root");
    el.createEl("h2", { cls: "kanban-done-title", text: "All Done Todos" });
    const entries = [];
    const files = this.app.vault.getFiles().filter((f) => f.extension === "kanban");
    for (const file of files) {
      try {
        const raw = await this.app.vault.read(file);
        const board = JSON.parse(raw);
        if (!(board == null ? void 0 : board.columns))
          continue;
        for (const col of board.columns) {
          if (!col.isDone)
            continue;
          for (const card of col.cards) {
            entries.push({
              card,
              boardName: file.basename,
              columnName: col.name,
              completedAt: (_a = card.completedAt) != null ? _a : card.createdAt
            });
          }
        }
      } catch (e) {
      }
    }
    if (entries.length === 0) {
      el.createEl("div", { cls: "kanban-done-empty", text: "No completed todos yet. Mark a column as 'Done' on your board and complete some tasks!" });
      return;
    }
    entries.sort((a, b) => b.completedAt - a.completedAt);
    const groups = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      const dateKey = new Date(entry.completedAt).toLocaleDateString("en-GB", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
      if (!groups.has(dateKey))
        groups.set(dateKey, []);
      groups.get(dateKey).push(entry);
    }
    el.createEl("div", { cls: "kanban-done-count", text: `${entries.length} completed todo${entries.length !== 1 ? "s" : ""} across ${files.length} board${files.length !== 1 ? "s" : ""}` });
    for (const [dateKey, dayEntries] of groups) {
      const section = el.createEl("div", { cls: "kanban-done-section" });
      section.createEl("div", { cls: "kanban-done-date-hdr", text: dateKey });
      for (const entry of dayEntries) {
        const row = section.createEl("div", { cls: "kanban-done-row" });
        const check = row.createEl("span", { cls: "kanban-done-check" });
        check.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg>`;
        const main = row.createEl("div", { cls: "kanban-done-main" });
        main.createEl("span", { cls: "kanban-done-card-title", text: entry.card.title });
        if (entry.card.description) {
          main.createEl("span", { cls: "kanban-done-card-desc", text: entry.card.description });
        }
        const meta = row.createEl("div", { cls: "kanban-done-meta" });
        const cardLabels = this.plugin.settings.labels.filter((l) => {
          var _a2;
          return (_a2 = entry.card.labelIds) == null ? void 0 : _a2.includes(l.id);
        });
        cardLabels.forEach((l) => {
          const tag = meta.createEl("span", { cls: "kanban-label-tag", text: l.name });
          tag.style.setProperty("--lc", l.color);
        });
        meta.createEl("span", { cls: "kanban-done-board", text: entry.boardName });
        const time = new Date(entry.completedAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
        meta.createEl("span", { cls: "kanban-done-time", text: time });
      }
    }
  }
};
var SKILL_CHART_VIEW_TYPE = "kanban-skill-chart";
var KanbanSkillChartView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.compareFrom = toDateInputVal(new Date(Date.now() - 7 * 864e5));
    this.compareTo = toDateInputVal(new Date());
    this.compareEnabled = true;
    this.plugin = plugin;
  }
  getViewType() {
    return SKILL_CHART_VIEW_TYPE;
  }
  getDisplayText() {
    return "Skill Chart";
  }
  getIcon() {
    return "activity";
  }
  async onOpen() {
    await this.maybeSnapshot();
    this.render();
  }
  async onClose() {
  }
  async maybeSnapshot() {
    const { skillData } = this.plugin.settings;
    const now = Date.now();
    const last = skillData.snapshots[skillData.snapshots.length - 1];
    if (!last || now - last.timestamp > 20 * 60 * 60 * 1e3) {
      skillData.snapshots.push({ timestamp: now, scores: { ...skillData.scores } });
      if (skillData.snapshots.length > 500)
        skillData.snapshots.splice(0, skillData.snapshots.length - 500);
      await this.plugin.saveSettings();
    }
  }
  closestSnapshot(ts) {
    const snaps = this.plugin.settings.skillData.snapshots;
    if (!snaps.length)
      return null;
    return snaps.reduce(
      (best, s) => Math.abs(s.timestamp - ts) < Math.abs(best.timestamp - ts) ? s : best
    );
  }
  render() {
    const el = this.contentEl;
    el.empty();
    el.addClass("kanban-skill-root");
    const { labels, skillData } = this.plugin.settings;
    const { scores } = skillData;
    el.createEl("h2", { cls: "kanban-skill-title", text: "Skill Chart" });
    const rangeSection = el.createEl("div", { cls: "kanban-skill-range" });
    const rangeHeader = rangeSection.createEl("div", { cls: "kanban-skill-range-hdr" });
    rangeHeader.createEl("span", { cls: "kanban-skill-range-label", text: "Compare with period" });
    const toggleWrap = rangeHeader.createEl("label", { cls: "kanban-skill-toggle" });
    const toggleInput = toggleWrap.createEl("input", { attr: { type: "checkbox" } });
    toggleInput.checked = this.compareEnabled;
    toggleWrap.createEl("span", { cls: "kanban-skill-toggle-track" });
    toggleInput.addEventListener("change", () => {
      this.compareEnabled = toggleInput.checked;
      this.render();
    });
    if (this.compareEnabled) {
      const rangeInputs = rangeSection.createEl("div", { cls: "kanban-skill-range-inputs" });
      const presets = rangeInputs.createEl("div", { cls: "kanban-skill-presets" });
      [{ label: "1W", days: 7 }, { label: "2W", days: 14 }, { label: "1M", days: 30 }, { label: "3M", days: 90 }, { label: "6M", days: 180 }].forEach((p) => {
        const now = new Date();
        const fromDate = new Date(now.getTime() - p.days * 864e5);
        const isActive = this.compareFrom === toDateInputVal(fromDate) && this.compareTo === toDateInputVal(now);
        const btn = presets.createEl("button", { cls: "kanban-skill-preset-btn" + (isActive ? " active" : ""), text: p.label });
        btn.addEventListener("click", () => {
          this.compareFrom = toDateInputVal(new Date(Date.now() - p.days * 864e5));
          this.compareTo = toDateInputVal(new Date());
          this.render();
        });
      });
      const dateRow = rangeInputs.createEl("div", { cls: "kanban-skill-date-row" });
      dateRow.createEl("span", { cls: "kanban-skill-date-sep", text: "From" });
      const fromInput = dateRow.createEl("input", { cls: "kanban-skill-date-input", attr: { type: "date", value: this.compareFrom, max: this.compareTo } });
      dateRow.createEl("span", { cls: "kanban-skill-date-sep", text: "to" });
      const toInput = dateRow.createEl("input", { cls: "kanban-skill-date-input", attr: { type: "date", value: this.compareTo, max: toDateInputVal(new Date()) } });
      fromInput.addEventListener("change", () => {
        if (fromInput.value) {
          this.compareFrom = fromInput.value;
          this.render();
        }
      });
      toInput.addEventListener("change", () => {
        if (toInput.value) {
          this.compareTo = toInput.value;
          this.render();
        }
      });
    }
    if (labels.length === 0) {
      el.createEl("div", { cls: "kanban-skill-empty", text: "No labels defined. Add labels in the plugin settings to use the Skill Chart." });
      return;
    }
    let compareScores = null;
    let compareLabel = "";
    if (this.compareEnabled) {
      const fromTs = new Date(this.compareFrom).getTime();
      const fromSnap = this.closestSnapshot(fromTs);
      if (fromSnap) {
        compareScores = fromSnap.scores;
        const fromFmt = new Date(this.compareFrom).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
        const toFmt = new Date(this.compareTo).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
        compareLabel = `${fromFmt} \u2013 ${toFmt}`;
      }
    }
    const allVals = labels.map((l) => {
      var _a;
      return (_a = scores[l.id]) != null ? _a : 0;
    });
    const cmpVals = compareScores ? labels.map((l) => {
      var _a;
      return (_a = compareScores[l.id]) != null ? _a : 0;
    }) : [];
    const rawMax = Math.max(...allVals, ...cmpVals, 1);
    const scale = rawMax <= 5 ? 5 : rawMax <= 10 ? 10 : Math.ceil(rawMax / 5) * 5;
    const chartWrap = el.createEl("div", { cls: "kanban-skill-chart-wrap" });
    chartWrap.innerHTML = this.buildRadar(labels, scores, compareScores, scale);
    if (compareScores && compareLabel) {
      const legend = el.createEl("div", { cls: "kanban-skill-legend" });
      const cur = legend.createEl("div", { cls: "kanban-skill-legend-item" });
      cur.createEl("span", { cls: "kanban-skill-legend-line current" });
      cur.createEl("span", { text: "Now" });
      const cmp = legend.createEl("div", { cls: "kanban-skill-legend-item" });
      cmp.createEl("span", { cls: "kanban-skill-legend-line compare" });
      cmp.createEl("span", { text: compareLabel });
    }
    const statsGrid = el.createEl("div", { cls: "kanban-skill-stats" });
    labels.forEach((label) => {
      var _a, _b;
      const cur = (_a = scores[label.id]) != null ? _a : 0;
      const cmp = (_b = compareScores == null ? void 0 : compareScores[label.id]) != null ? _b : 0;
      const delta = cur - cmp;
      const stat = statsGrid.createEl("div", { cls: "kanban-skill-stat" });
      stat.style.setProperty("--lc", label.color);
      stat.createEl("span", { cls: "kanban-skill-stat-dot" });
      stat.createEl("span", { cls: "kanban-skill-stat-name", text: label.name });
      stat.createEl("span", { cls: "kanban-skill-stat-val", text: String(cur) });
      if (compareScores && delta !== 0) {
        stat.createEl("span", { cls: `kanban-skill-stat-delta ${delta > 0 ? "pos" : "neg"}`, text: delta > 0 ? `+${delta}` : String(delta) });
      }
    });
    const total = allVals.reduce((a, b) => a + b, 0);
    const cmpTotal = cmpVals.reduce((a, b) => a + b, 0);
    const totalDelta = total - cmpTotal;
    const totalRow = el.createEl("div", { cls: "kanban-skill-total" });
    totalRow.createEl("span", { text: "Total completions: " });
    totalRow.createEl("strong", { text: String(total) });
    if (compareScores && totalDelta !== 0) {
      totalRow.createEl("span", { cls: `kanban-skill-stat-delta ${totalDelta > 0 ? "pos" : "neg"}`, text: totalDelta > 0 ? ` +${totalDelta}` : ` ${totalDelta}` });
    }
  }
  buildRadar(labels, scores, compareScores, scale) {
    const N = labels.length;
    const size = 300;
    const cx = size / 2, cy = size / 2;
    const maxR = 90;
    const angles = labels.map((_, i) => 2 * Math.PI * i / N - Math.PI / 2);
    const pt = (a, r) => `${(cx + r * Math.cos(a)).toFixed(2)},${(cy + r * Math.sin(a)).toFixed(2)}`;
    const ptObj = (a, r) => ({ x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) });
    const charWidth = 6.5;
    const lineH = 14;
    const labelPad = 24;
    const maxLabelLen = 12;
    const padSides = { top: 32, right: 32, bottom: 32, left: 32 };
    labels.forEach((l, i) => {
      const lines = wrapText(l.name, maxLabelLen);
      const textW = Math.max(...lines.map((ln) => ln.length)) * charWidth;
      const textH = lines.length * lineH;
      const lp = ptObj(angles[i], maxR + labelPad);
      const anchor = Math.abs(lp.x - cx) < 12 ? "middle" : lp.x < cx ? "end" : "start";
      if (anchor === "start") {
        const re = lp.x + textW - size;
        if (re > padSides.right)
          padSides.right = re + 8;
      } else if (anchor === "end") {
        const le = -lp.x + textW;
        if (le > padSides.left)
          padSides.left = le + 8;
      } else {
        const hw = textW / 2;
        const re = lp.x + hw - size;
        const le = -lp.x + hw;
        if (re > padSides.right)
          padSides.right = re + 8;
        if (le > padSides.left)
          padSides.left = le + 8;
      }
      const topEdge = -lp.y + textH;
      const botEdge = lp.y + textH - size;
      if (topEdge > padSides.top)
        padSides.top = topEdge + 8;
      if (botEdge > padSides.bottom)
        padSides.bottom = botEdge + 8;
    });
    let grid = "";
    for (let lvl = 1; lvl <= 4; lvl++) {
      const r = lvl / 4 * maxR;
      grid += `<polygon points="${angles.map((a) => pt(a, r)).join(" ")}" fill="none" stroke="currentColor" stroke-opacity="0.07" stroke-width="1"/>`;
      const val = Math.round(lvl / 4 * scale);
      const top = ptObj(angles[0], r);
      grid += `<text x="${(top.x + 3).toFixed(1)}" y="${(top.y - 3).toFixed(1)}" font-size="8" opacity="0.3" fill="currentColor">${val}</text>`;
    }
    const axes = angles.map((a) => {
      const p = ptObj(a, maxR);
      return `<line x1="${cx}" y1="${cy}" x2="${p.x.toFixed(1)}" y2="${p.y.toFixed(1)}" stroke="currentColor" stroke-opacity="0.1" stroke-width="1"/>`;
    }).join("");
    const dataPts = labels.map((l, i) => {
      var _a;
      const r = Math.min((_a = scores[l.id]) != null ? _a : 0, scale) / scale * maxR;
      return pt(angles[i], r);
    }).join(" ");
    const dataDots = labels.map((l, i) => {
      var _a;
      const r = Math.min((_a = scores[l.id]) != null ? _a : 0, scale) / scale * maxR;
      return ptObj(angles[i], r);
    });
    let cmpPoly = "";
    if (compareScores) {
      const cPts = labels.map((l, i) => {
        var _a;
        const r = Math.min((_a = compareScores[l.id]) != null ? _a : 0, scale) / scale * maxR;
        return pt(angles[i], r);
      }).join(" ");
      cmpPoly = `<polygon points="${cPts}" fill="currentColor" fill-opacity="0.05" stroke="currentColor" stroke-opacity="0.3" stroke-width="1.5" stroke-dasharray="4,3"/>`;
    }
    const dataPoly = `<polygon points="${dataPts}" fill="var(--interactive-accent)" fill-opacity="0.15" stroke="var(--interactive-accent)" stroke-width="2"/>`;
    const dots = dataDots.map((p) => `<circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="3.5" fill="var(--interactive-accent)" stroke="var(--background-primary)" stroke-width="1.5"/>`).join("");
    const axisLabels = labels.map((l, i) => {
      var _a;
      const a = angles[i];
      const lp = ptObj(a, maxR + labelPad - 4);
      const tp = ptObj(a, maxR + labelPad + 6);
      const anchor = Math.abs(lp.x - cx) < 12 ? "middle" : lp.x < cx ? "end" : "start";
      const lines = wrapText(l.name, maxLabelLen);
      let nameText = `<text text-anchor="${anchor}" font-size="11" font-weight="600" fill="currentColor">`;
      lines.forEach((line, li) => {
        nameText += `<tspan x="${tp.x.toFixed(1)}" y="${(tp.y - 4 + li * lineH).toFixed(1)}">${escSvg(line)}</tspan>`;
      });
      nameText += `</text>`;
      const scoreY = tp.y - 4 + lines.length * lineH + 2;
      const scoreText = `<text x="${tp.x.toFixed(1)}" y="${scoreY.toFixed(1)}" text-anchor="${anchor}" font-size="10" fill="currentColor" opacity="0.4">${(_a = scores[l.id]) != null ? _a : 0}</text>`;
      const dot = `<circle cx="${lp.x.toFixed(1)}" cy="${(lp.y - 2).toFixed(1)}" r="3" fill="${l.color}"/>`;
      return dot + nameText + scoreText;
    }).join("");
    const vbX = -padSides.left, vbY = -padSides.top;
    const vbW = size + padSides.left + padSides.right, vbH = size + padSides.top + padSides.bottom;
    return `<svg viewBox="${vbX.toFixed(0)} ${vbY.toFixed(0)} ${vbW.toFixed(0)} ${vbH.toFixed(0)}" xmlns="http://www.w3.org/2000/svg" style="width:100%;max-width:420px;display:block;margin:0 auto">${grid}${axes}${cmpPoly}${dataPoly}${dots}${axisLabels}</svg>`;
  }
};
var InputModal = class extends import_obsidian.Modal {
  constructor(app, title, def, cb) {
    super(app);
    this.title = title;
    this.def = def;
    this.cb = cb;
  }
  onOpen() {
    const { contentEl: el } = this;
    el.addClass("kanban-modal");
    el.createEl("h3", { cls: "kanban-modal-title", text: this.title });
    const input = el.createEl("input", { cls: "kanban-modal-input", attr: { type: "text", value: this.def } });
    input.focus();
    input.select();
    const btns = el.createEl("div", { cls: "kanban-modal-btns" });
    btns.createEl("button", { cls: "kb-btn kb-btn-ghost", text: "Cancel" }).addEventListener("click", () => this.close());
    const ok = btns.createEl("button", { cls: "kb-btn kb-btn-primary", text: "OK" });
    ok.addEventListener("click", () => {
      const v = input.value.trim();
      if (v) {
        this.cb(v);
        this.close();
      }
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        ok.click();
      if (e.key === "Escape")
        this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ColumnModal = class extends import_obsidian.Modal {
  constructor(app, opts, cb) {
    super(app);
    this.opts = opts;
    this.cb = cb;
  }
  onOpen() {
    var _a;
    const { contentEl: el } = this;
    el.addClass("kanban-modal");
    el.createEl("h3", { cls: "kanban-modal-title", text: "Column settings" });
    el.createEl("label", { cls: "kanban-modal-label", text: "Name" });
    const nameInput = el.createEl("input", { cls: "kanban-modal-input", attr: { type: "text", value: this.opts.name } });
    nameInput.focus();
    nameInput.select();
    const doneRow = el.createEl("div", { cls: "kanban-modal-done-row" });
    doneRow.createEl("div", { cls: "kanban-modal-done-info" }).createEl("span", { cls: "kanban-modal-label", text: "Mark as Done column" });
    (_a = doneRow.querySelector(".kanban-modal-label")) == null ? void 0 : _a.createEl("span", { cls: "kanban-modal-done-hint", text: "Cards here count in Skill Chart & All Done Todos" });
    const toggleWrap = doneRow.createEl("label", { cls: "kanban-skill-toggle" });
    const toggleInput = toggleWrap.createEl("input", { attr: { type: "checkbox" } });
    toggleInput.checked = this.opts.isDone;
    toggleWrap.createEl("span", { cls: "kanban-skill-toggle-track" });
    const btns = el.createEl("div", { cls: "kanban-modal-btns" });
    btns.createEl("button", { cls: "kb-btn kb-btn-ghost", text: "Cancel" }).addEventListener("click", () => this.close());
    const ok = btns.createEl("button", { cls: "kb-btn kb-btn-primary", text: "OK" });
    ok.addEventListener("click", () => {
      const name = nameInput.value.trim();
      if (!name)
        return;
      this.cb({ name, isDone: toggleInput.checked });
      this.close();
    });
    nameInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        ok.click();
      if (e.key === "Escape")
        this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CardModal = class extends import_obsidian.Modal {
  constructor(app, allLabels, card, cb) {
    super(app);
    this.allLabels = allLabels;
    this.card = card;
    this.cb = cb;
  }
  onOpen() {
    var _a, _b, _c, _d, _e;
    const { contentEl: el } = this;
    el.addClass("kanban-modal");
    el.createEl("h3", { cls: "kanban-modal-title", text: this.card ? "Edit card" : "New card" });
    el.createEl("label", { cls: "kanban-modal-label", text: "Title" });
    const titleInput = el.createEl("input", { cls: "kanban-modal-input", attr: { type: "text", value: (_b = (_a = this.card) == null ? void 0 : _a.title) != null ? _b : "", placeholder: "Task title\u2026" } });
    titleInput.focus();
    el.createEl("label", { cls: "kanban-modal-label", text: "Description" });
    const descInput = el.createEl("textarea", { cls: "kanban-modal-textarea", attr: { placeholder: "Optional details\u2026", rows: "3" } });
    if ((_c = this.card) == null ? void 0 : _c.description)
      descInput.value = this.card.description;
    const selected = new Set((_e = (_d = this.card) == null ? void 0 : _d.labelIds) != null ? _e : []);
    if (this.allLabels.length) {
      el.createEl("label", { cls: "kanban-modal-label", text: "Labels" });
      const grid = el.createEl("div", { cls: "kanban-modal-chips" });
      this.allLabels.forEach((label) => {
        const chip = grid.createEl("div", { cls: "kanban-modal-chip" + (selected.has(label.id) ? " selected" : "") });
        chip.style.setProperty("--lc", label.color);
        chip.createEl("span", { cls: "kanban-chip-dot" });
        chip.createEl("span", { text: label.name });
        chip.addEventListener("click", () => {
          if (selected.has(label.id)) {
            selected.delete(label.id);
            chip.removeClass("selected");
          } else {
            selected.add(label.id);
            chip.addClass("selected");
          }
        });
      });
    }
    const btns = el.createEl("div", { cls: "kanban-modal-btns" });
    btns.createEl("button", { cls: "kb-btn kb-btn-ghost", text: "Cancel" }).addEventListener("click", () => this.close());
    const save = btns.createEl("button", { cls: "kb-btn kb-btn-primary", text: this.card ? "Save" : "Create" });
    save.addEventListener("click", () => {
      const t = titleInput.value.trim();
      if (!t) {
        new import_obsidian.Notice("Please enter a title.");
        return;
      }
      this.cb(t, descInput.value.trim(), Array.from(selected));
      this.close();
    });
    titleInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        save.click();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var KanbanTodoPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(KANBAN_VIEW_TYPE, (leaf) => new KanbanView(leaf, this));
    this.registerExtensions(["kanban"], KANBAN_VIEW_TYPE);
    this.registerView(SKILL_CHART_VIEW_TYPE, (leaf) => new KanbanSkillChartView(leaf, this));
    this.registerView(ALL_DONE_VIEW_TYPE, (leaf) => new AllDoneTodosView(leaf, this));
    this.addRibbonIcon("layout-dashboard", "New Kanban Board", () => this.createBoard());
    this.addRibbonIcon("check-square", "All Done Todos", () => this.openView(ALL_DONE_VIEW_TYPE));
    this.addRibbonIcon("activity", "Skill Chart", () => this.openView(SKILL_CHART_VIEW_TYPE));
    this.addCommand({ id: "create-kanban-board", name: "New Kanban Board", callback: () => this.createBoard() });
    this.addCommand({ id: "open-skill-chart", name: "Open Skill Chart", callback: () => this.openView(SKILL_CHART_VIEW_TYPE) });
    this.addCommand({ id: "open-all-done", name: "Open All Done Todos", callback: () => this.openView(ALL_DONE_VIEW_TYPE) });
    this.addSettingTab(new KanbanSettingTab(this.app, this));
  }
  async createBoard() {
    new InputModal(this.app, "New board", "My Board", async (name) => {
      const path = `${name}.kanban`;
      if (this.app.vault.getAbstractFileByPath(path)) {
        new import_obsidian.Notice(`"${path}" already exists.`);
        return;
      }
      const file = await this.app.vault.create(path, JSON.stringify(defaultBoard(), null, 2));
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
    }).open();
  }
  async openView(type) {
    const existing = this.app.workspace.getLeavesOfType(type)[0];
    if (existing) {
      this.app.workspace.revealLeaf(existing);
      return;
    }
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.setViewState({ type, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async updateSkillScores(labelIds, delta) {
    var _a;
    for (const id of labelIds) {
      this.settings.skillData.scores[id] = Math.max(0, ((_a = this.settings.skillData.scores[id]) != null ? _a : 0) + delta);
    }
    await this.saveSettings();
    this.app.workspace.getLeavesOfType(SKILL_CHART_VIEW_TYPE).forEach((l) => l.view.render());
  }
  refreshAllDoneView() {
    this.app.workspace.getLeavesOfType(ALL_DONE_VIEW_TYPE).forEach((l) => l.view.render());
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    if (!this.settings.labels)
      this.settings.labels = DEFAULT_SETTINGS.labels;
    if (!this.settings.skillData)
      this.settings.skillData = { scores: {}, snapshots: [] };
    if (!this.settings.skillData.snapshots)
      this.settings.skillData.snapshots = [];
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var PRESET_COLORS = ["#ef4444", "#f97316", "#f59e0b", "#84cc16", "#10b981", "#06b6d4", "#6366f1", "#8b5cf6", "#ec4899"];
var KanbanSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl: el } = this;
    el.empty();
    el.addClass("kanban-settings");
    el.createEl("h2", { text: "Kanban Todo Board" });
    el.createEl("p", { cls: "setting-item-description", text: "Labels are assigned to cards and drive the Skill Chart." });
    el.createEl("h3", { cls: "kanban-settings-h3", text: "Labels" });
    const list = el.createEl("div", { cls: "kanban-settings-labels" });
    this.renderLabels(list);
    new import_obsidian.Setting(el).addButton(
      (b) => b.setButtonText("+ Add label").setCta().onClick(async () => {
        this.plugin.settings.labels.push({ id: generateId(), name: "New Label", color: PRESET_COLORS[this.plugin.settings.labels.length % PRESET_COLORS.length] });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    el.createEl("h3", { cls: "kanban-settings-h3", text: "Skill Data" });
    new import_obsidian.Setting(el).setName("Reset skill scores").setDesc("Clears all accumulated scores and history.").addButton((b) => b.setButtonText("Reset").setWarning().onClick(async () => {
      this.plugin.settings.skillData = { scores: {}, snapshots: [] };
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Skill scores reset.");
    }));
  }
  renderLabels(container) {
    container.empty();
    this.plugin.settings.labels.forEach((label, idx) => {
      const row = container.createEl("div", { cls: "kanban-settings-row" });
      const colorInput = row.createEl("input", { cls: "kanban-settings-color", attr: { type: "color", value: label.color } });
      colorInput.addEventListener("input", async () => {
        label.color = colorInput.value;
        await this.plugin.saveSettings();
        preview.style.setProperty("--lc", colorInput.value);
      });
      const nameInput = row.createEl("input", { cls: "kanban-settings-name", attr: { type: "text", value: label.name } });
      nameInput.addEventListener("change", async () => {
        label.name = nameInput.value.trim() || label.name;
        await this.plugin.saveSettings();
      });
      nameInput.addEventListener("input", () => {
        preview.textContent = nameInput.value || label.name;
      });
      const preview = row.createEl("span", { cls: "kanban-label-tag", text: label.name });
      preview.style.setProperty("--lc", label.color);
      const del = row.createEl("button", { cls: "kb-icon-btn kb-icon-danger", attr: { title: "Remove" } });
      del.innerHTML = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;
      del.addEventListener("click", async () => {
        this.plugin.settings.labels.splice(idx, 1);
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
};
